name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sign up to Netlify
        run: |
          EMAIL=${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com
          CODE=${{ secrets.GITHUB_CODE }}
          SITE_NAME=${{ secrets.NETLIFY_SITE_NAME }}
          echo "Email: $EMAIL"
          echo "Code: $CODE"
          echo "Site name: $SITE_NAME"
          echo "Creating account..."
          # Sign up to Netlify
          response=$(curl -s -X POST "https://api.netlify.com/api/v1/users/oauth/github" \
            -H "Content-Type: application/json" \
            -d "{\"email\":\"$EMAIL\",\"code\":\"$CODE\",\"site_name\":\"$SITE_NAME\"}")
          echo "Account created: $response"
          # Extract the site_id and access_token from the response
          SITE_ID=$(echo $response | jq -r '.site_id')
          ACCESS_TOKEN=$(echo $response | jq -r '.access_token')
          echo "::set-output name=site_id::$SITE_ID"
          echo "::set-output name=access_token::$ACCESS_TOKEN"
        id: signup

      - name: Deploy to Netlify
        uses: netlify/actions/cli@latest
        with:
          args: deploy --auth=${{ steps.signup.outputs.access_token }} --site=${{ steps.signup.outputs.site_id }} --dir=.
