name: Create Netlify Account and Deploy

on:
  push:
    branches:
      - main

jobs:
  create-account:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure netlify-cli
      run: |
        npm install -g netlify-cli

    - name: Create Netlify Account
      run: netlify signup --github
      
    - name: Retrieve Auth Token
      run: netlify api access_token.create
      env:
        NETLIFY_AUTH_TOKEN: ${{ steps.retrieve_auth_token.outputs.token }}
        
    - name: Retrieve Site ID
      run: netlify api sites.list
      env:
        NETLIFY_SITE_ID: ${{ steps.retrieve_site_id.outputs.id }}
        
    - name: Deploy to Netlify
      run: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir=. --prod
