name: Sign up and Deploy

on:
  push:
    branches:
      - main

jobs:
  create-account:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install commander
      run: |
        npm install commander        
    - name: Install jq
      run: |
        npm install -g jq

    - name: Sign up to Netlify
      run: |
        NETLIFY_RESPONSE=$(curl -X POST -d '' -H "Content-Type: application/json" -H "Authorization: Bearer ${GITHUB_TOKEN}" https://api.netlify.com/api/v1/users/oauth/github)
        ACCESS_TOKEN=$(echo $NETLIFY_RESPONSE | jq -r .access_token)
        echo "Netlify access token is ${ACCESS_TOKEN}"
        echo "NETLIFY_ACCESS_TOKEN" ${ACCESS_TOKEN} >> $GITHUB_ENV
        SITE_ID=$(echo $NETLIFY_RESPONSE | jq -r .site_id)
        echo "Netlify site ID is ${SITE_ID}"
        echo "NETLIFY_SITE_ID" ${SITE_ID} >> $GITHUB_ENV
